---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: block
  namespace: smoke-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: block
  volumeMode: Block
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filesystem
  namespace: smoke-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: filesystem
  volumeMode: Filesystem
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: object
  namespace: smoke-test
spec:
  additionalConfig:
    maxSize: 1G
  bucketName: object
  storageClassName: object
