apiVersion: v1
baseDomain: example.com
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: control
  replicas: 3
metadata:
  name: okd
networking:
  clusterNetworks:
  - cidr: 10.100.0.0/14
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: |
  PULL_SECRET
sshKey: 'SSH_PUBLIC_KEY'
additionalTrustBundle: |
  SELF_SIGNED_CERT
imageContentSources:
- mirrors:
  - services.okd.example.com:5000/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - services.okd.example.com:5000/openshift/okd
  source: quay.io/openshift/okd-content
