apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: compute
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - compute
  maxUnavailable: 1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/compute: ""
  paused: false
