apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: storage
spec:
  machineConfigSelector:
    matchExpressions:
    - key: machineconfiguration.openshift.io/role
      operator: In
      values:
      - worker
      - storage
  maxUnavailable: 1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/storage: ""
  paused: false
