apiVersion: v1
baseDomain: {{ BASE_DOMAIN }}
compute:
- hyperthreading: Enabled
  name: worker
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  replicas: 3
metadata:
  name: {{ SUB_DOMAIN }}
networking:
  clusterNetworks:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  defaultNetwork:
    type: OVNKubernetes
    ovnKubernetesConfig:
      genevePort: 6081
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
fips: true
pullSecret: '{{ PULL_SECRET }}'
sshKey: '{{ SSH_PUBLIC_KEY }}'
additionalTrustBundle: |
{{ REGISTRY_CERT }}
imageContentSources:
- mirrors:
  - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/openshift/okd
  source: quay.io/openshift/okd
- mirrors:
  - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/openshift/okd
  source: quay.io/openshift/okd-content
