---
apiVersion: imageregistry.operator.openshift.io/v1
kind: Config
metadata:
  finalizers:
    - imageregistry.operator.openshift.io/finalizer
  name: cluster
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: docker-registry
                operator: In
                values:
                  - default
          namespaces:
            - openshift-image-registry
          topologyKey: kubernetes.io/hostname
  logLevel: Normal
  managementState: Managed
  nodeSelector:
    node-role.kubernetes.io/infra: ''
  observedConfig: null
  operatorLogLevel: Normal
  proxy: {}
  replicas: 3
  requests:
    read:
      maxWaitInQueue: 0s
    write:
      maxWaitInQueue: 0s
  rolloutStrategy: RollingUpdate
  storage:
    pvc:
      claim: null
  unsupportedConfigOverrides: null
