---
apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: rook-ceph
spec:
  repositoryDigestMirrors:
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/rook/ceph
      source: docker.io/rook/ceph
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/ceph/ceph
      source: quay.io/ceph/ceph
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/cephcsi/cephcsi
      source: quay.io/cephcsi/cephcsi
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/sig-storage/csi-node-driver-registrar
      source: registry.k8s.io/sig-storage/csi-node-driver-registrar
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/sig-storage/csi-resizer
      source: registry.k8s.io/sig-storage/csi-resizer
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/sig-storage/csi-provisioner
      source: registry.k8s.io/sig-storage/csi-provisioner
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/sig-storage/csi-snapshotter
      source: registry.k8s.io/sig-storage/csi-snapshotter
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/sig-storage/csi-attacher
      source: registry.k8s.io/sig-storage/csi-attacher
    - mirrors:
        - services.{{ SUB_DOMAIN }}.{{ BASE_DOMAIN }}:5000/csiaddons/volumereplication-operator
      source: quay.io/csiaddons/volumereplication-operator
