---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: upstream-community-operators
  namespace: openshift-marketplace
spec:
  displayName: Upstream Community Operators
  image: services.okd.example.com:5000/upstream-community-operators/upstream-community-operators:latest
  publisher: Community
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m
