---
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: no-issue-activity
          stale-issue-message: Stale issue message
          stale-pr-label: no-pr-activity
          stale-pr-message: Stale pull request message
name: Mark stale issues and pull requests
on:
  schedule:
    - cron: 30 1 * * *
